name: place_stone

on:
  issues:
    types: [opened]

jobs:
  place_stone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo label name
      run: echo ${{ github.event.label.name }}
