name: Place stone.
on:
  issues:
    types:
      - opened
jobs:
  place-stone:
    if: ${{ startsWith( github.event.issue.title, '.' ) != true }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Run python file
        run: echo "RESULT=$(python othello.py ${{ github.event.issue.title }} ${{ github.event.issue.user.login }} )" >> $GITHUB_ENV

      - name: Commit and push placed stone
        if: ${{ env.RESULT == 'successfully placed your stone!' }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add README.md
          git commit -m "Placed stone in `date +"%Y-%m-%d %H:%M"`"
          git push

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ env.RESULT }}
            
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "closed issue! bye!"
