name: Place stone.
on:
  issues:
    types:
      - labeled
jobs:
  place-stone:
    if: github.event.label.name == 'place stone'

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Run python file
        run: echo "RESULT=$(python othello.py ${{ github.event.issue.title }} ${{ github.event.issue.user.login }} )" >> $GITHUB_ENV

      - name: Commit placed stone
        if: ${{ env.RESULT == 'successfully placed your stone!' }}
        run: |
          git config --local user.name "${{ env.GIT_USERNAME }}"
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git add README.md
          git commit -m "Placed stone in `date +"%Y-%m-%d %H:%M"`"
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --force --quiet "https://${{ env.GIT_USERNAME }}:${{ secrets.GH_ACCESS_TOKEN }}@${{ env.DEPLOY_URL }}" master:master

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ env.RESULT }}
